### ISSUE TITLE
luci-app-eoip not appear in the application menu to choose

### ISSUE THREAD

**Issue by springtales** [bogdik/luci-app-eoip#1]
hi
the luci-app-eoip not appear in the application menu to choose ,
also I got error
( ERROR: please fix package/feeds/luci/luci-app-eoip/Makefile - see logs/package/feeds/luci/luci-app-eoip/dump.txt for details
Collecting package info: done )

in the dump.txt
( Makefile:12: ../../luci.mk: No such file or directory
make[2]: *** No rule to make target `../../luci.mk'. Stop.)

I follow your guide accurately
any help pls
thanks

**Comment by bogdik** [comment]
Please use https://github.com/openwrt/luci/tree/master/applications/luci-app-eoip
